name: Publish Nuget package

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  DOTNET_SDK_VERSION: '10.0.x'
  DOTNET_TFM: 'net10.0'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_SDK_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: 'Build'
        run: dotnet build --configuration Release

      - name: 'Test'
        run: dotnet test --configuration Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --no-restore --verbosity normal

      - name: Publish NuGet package
        run: dotnet nuget push ./Naturally/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_PAT }} --source https://api.nuget.org/v3/index.json --skip-duplicate